name: Run Tests

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip pandas
          python -m pip install --upgrade pip openpyxl

      - name: Set execute permissions for tests.sh
        run: chmod +x tests.sh

      - name: Run Tests
        run: |
          set -e  # Exit immediately if a command returns a non-zero status code
          ./tests.sh
          exit_status=$?
          if [ $exit_status -ne 0 ]; then
            echo "Some tests failed"
            exit $exit_status
          fi